---
- name: ensure atd and crond services are running
  hosts: servera.lab.example.com
  gather_facts: false

  tasks:
    - name: check for atd
      ansible.builtin.service:
        name: atd
        state: started

    - name: check for crond
      ansible.builtin.service:
        name: crond
        state: started
...
