---
- name: try forced change or failure
  hosts: servera.lab.example.com
  gather_facts: false
  force_handlers: true

  tasks:
    - name: task 1
      ansible.builtin.command: hostname
      register: hostname_out
      failed_when: '"servera" in hostname_out["stdout"]'
      #changed_when: '"servera" in hostname_out["stdout"]'
      #changed_when: false

    - name: display command output
      ansible.builtin.debug:
        var: hostname_out

...
