---
- name: check out secret variables
  hosts: servera.lab.example.com
  gather_facts: false

  vars_files:
    - secret-vars.yaml

  tasks:
    - name: show secret variables
      ansible.builtin.debug:
        msg: Decoded secrets are {{ first_name}} {{ last_name }}
...
