---
- name: try out a role
  hosts: servera.lab.example.com
  gather_facts: false

  roles:
    - role: student.myfirstrole
      greeting: hi folks

  pre_tasks:
    - name: say hello from tasks in playbook
      ansible.builtin.debug:
        msg: hello from the tasks section of use_role.yml

  
...
